"""empty message

Revision ID: 4deae3af24f4
Revises: 775f84c81bd6
Create Date: 2024-06-09 13:59:13.834339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4deae3af24f4'
down_revision = '775f84c81bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
