"""empty message

Revision ID: 7147e11c3218
Revises: 4deae3af24f4
Create Date: 2024-06-09 14:02:39.110506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7147e11c3218'
down_revision = '4deae3af24f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=40), nullable=True))

    # ### end Alembic commands ###
