"""empty message

Revision ID: 775f84c81bd6
Revises: c7afe9ebbf42
Create Date: 2024-06-06 21:00:16.677827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '775f84c81bd6'
down_revision = 'c7afe9ebbf42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('cat_photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cat_photo', mysql.VARCHAR(length=1000), nullable=True))

    # ### end Alembic commands ###
